### ISSUE TITLE
Add a docker image 

### ISSUE THREAD

**Issue by OlehBandrivskyi** [blocksecteam/rustle#10]
Hello,

I want to add Rustle to my CI pipelines. And it would be great to have an official and up-to-date docker image. 

Example of image integration to repository packages

_.github/workflows/image.yml_

```
name: Publish a docker image

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v3
        id: meta_rustle
        with:
          images: ghcr.io/blocksecteam/rustle

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta_rustle.outputs.tags }}
          labels: ${{ steps.meta_rustle.outputs.labels }}
```
